parameters:
    spectral_mandrill.mandrill.class: Spectral\MandrillBundle\Mandrill

services:
    spectral_mandrill.mandrill:
        class: "%spectral_mandrill.mandrill.class%"
        arguments: ["@logger", "%spectral_mandrill.api_key%"]
